//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class itemtoevent
    {
        public int Id { get; set; }
        public Nullable<int> CelebrationId { get; set; }
        public string Name { get; set; }
        public Nullable<double> Price { get; set; }
        public string Describe { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<bool> ToBeTaken { get; set; }
        public Nullable<bool> ToEveryone { get; set; }
    
        public virtual celebration celebration { get; set; }
    }
}
