//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PartyTeamEntities : DbContext
    {
        public PartyTeamEntities()
            : base("name=PartyTeamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<celebration> celebration { get; set; }
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<customerofevent> customerofevent { get; set; }
        public virtual DbSet<ItemOfList> ItemOfList { get; set; }
        public virtual DbSet<itemtoevent> itemtoevent { get; set; }
        public virtual DbSet<noteevent> noteevent { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<typeevent> typeevent { get; set; }
        public virtual DbSet<about> about { get; set; }
    }
}
